In [26]:
import numpy as np
#np.array([1,2,3])

In [27]:
a=np.array([1,2,3])

TypeError: 'list' object is not callable

In [28]:
b=np.array([1,2,3,4,3,4,5,6])

TypeError: 'list' object is not callable

In [29]:
a=np.array([1,2,3])

TypeError: 'list' object is not callable

In [30]:
a=np.array([1,2,4])

TypeError: 'list' object is not callable

In [31]:
a=np.array([1,2,3])

TypeError: 'list' object is not callable

In [32]:
np.ones(2)

array([1., 1.])

In [37]:
b=np.array=([1,2])

In [38]:
b

[1, 2]

In [40]:
c=np.array=([[1,2,3,3],[2,3,4,4]])

In [41]:
c

[[1, 2, 3, 3], [2, 3, 4, 4]]

In [43]:
np.ones([2,3,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [44]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [45]:
np.empty((3,2))

array([[3.44897822e-307, 4.45043631e-307],
       [1.89144519e-307, 2.22517741e-307],
       [4.45040236e-307, 4.67280789e-307]])

In [48]:
c=np.save('flkmglkrt',b)

In [49]:
c

[[1, 2, 3, 3], [2, 3, 4, 4]]

In [52]:
np.load('flkmglkrt.npy')

array([1, 2])

In [53]:
np.load(c.npy)

AttributeError: 'list' object has no attribute 'npy'

In [58]:
a=np.array=([[1,2,3,3],[4,5,5,6]])
b=np.array=([[2,3,4,5],[1,3,5,67]])


In [59]:
np.add(b,a)

array([[ 3,  5,  7,  8],
       [ 5,  8, 10, 73]])

In [60]:
np.multiply(b,a)

array([[  2,   6,  12,  15],
       [  4,  15,  25, 402]])

In [61]:
np.divide(b,a)

array([[ 2.        ,  1.5       ,  1.33333333,  1.66666667],
       [ 0.25      ,  0.6       ,  1.        , 11.16666667]])

In [62]:
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692,  20.08553692],
       [ 54.59815003, 148.4131591 , 148.4131591 , 403.42879349]])

In [63]:
np.sqrt(b)

array([[1.41421356, 1.73205081, 2.        , 2.23606798],
       [1.        , 1.73205081, 2.23606798, 8.18535277]])

In [64]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001,  0.14112001],
       [-0.7568025 , -0.95892427, -0.95892427, -0.2794155 ]])

In [65]:
np.cos(b)

array([[-0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.54030231, -0.9899925 ,  0.28366219, -0.5177698 ]])

In [66]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229, 1.09861229],
       [1.38629436, 1.60943791, 1.60943791, 1.79175947]])

In [68]:
a.dot(f)

AttributeError: 'list' object has no attribute 'dot'

In [69]:
#comparison
a==b

False

In [70]:
a<b

True

In [71]:
a>b

False

In [73]:
a<=b

True

In [74]:
a!=b

True

In [81]:
a=np.sum(a)

In [80]:
c

29

In [82]:
a

29

In [90]:
f=np.max(a)

In [93]:
f

29

In [94]:
d=np.min(a)

In [95]:
d

29

In [96]:
a

29

In [97]:
b

29

In [98]:
a==b

True

In [99]:
a<b

False

In [100]:
print(a)

29


In [101]:
a=np.array=([1,2,3,4],[1,2,3,4])

In [102]:
a

([1, 2, 3, 4], [1, 2, 3, 4])

In [103]:
b=([[1,4,4,5,67],[2,3,4,5]])

In [104]:
b

[[1, 4, 4, 5, 67], [2, 3, 4, 5]]

In [109]:
b=b.median=()

AttributeError: 'tuple' object has no attribute 'median'

In [113]:
np.std(b)

C:\Users\Raghav Jha\Anaco\lib\site-packages\numpy\core\_methods.py:140: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
C:\Users\Raghav Jha\Anaco\lib\site-packages\numpy\core\_methods.py:110: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
C:\Users\Raghav Jha\Anaco\lib\site-packages\numpy\core\_methods.py:132: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


nan

In [119]:
a.sort

AttributeError: 'tuple' object has no attribute 'sort'

In [120]:
a

([1, 2, 3, 4], [1, 2, 3, 4])

In [121]:
a[0:2]

([1, 2, 3, 4], [1, 2, 3, 4])

In [123]:
a[::-1]

([1, 2, 3, 4], [1, 2, 3, 4])

In [125]:
a.ravel()

AttributeError: 'tuple' object has no attribute 'ravel'

In [126]:
a

([1, 2, 3, 4], [1, 2, 3, 4])

In [127]:
np.hspilt(a,3)

AttributeError: module 'numpy' has no attribute 'hspilt'

In [128]:
np.vstack((a,b))

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [129]:
np.hsplit(a,3)

AttributeError: 'tuple' object has no attribute 'ndim'