In [1]:
import numpy as np

In [10]:
np.array([[1,2,3,4,45],[1,2,3,4]])

array([list([1, 2, 3, 4, 45]), list([1, 2, 3, 4])], dtype=object)

In [8]:
a

array([list([1, 2, 3, 4, 45]), list([1, 2, 3, 4])], dtype=object)

In [9]:
a

array([list([1, 2, 3, 4, 45]), list([1, 2, 3, 4])], dtype=object)

In [11]:
a=np.array([1,2,3])

In [12]:
a

array([1, 2, 3])

In [36]:
b=np.array([[4,5,6],[3,4,5,6]])

In [37]:
b

array([list([4, 5, 6]), list([3, 4, 5, 6])], dtype=object)

In [38]:
b=np.grid(([1,2,3],[4,5,6]))

AttributeError: module 'numpy' has no attribute 'grid'

In [39]:
b

array([list([4, 5, 6]), list([3, 4, 5, 6])], dtype=object)

In [40]:
np.concanate([grid,grid],axis=1)

AttributeError: module 'numpy' has no attribute 'concanate'

In [41]:
b=np.transpose(b)

In [42]:
b

array([list([4, 5, 6]), list([3, 4, 5, 6])], dtype=object)

In [43]:
i=np.Transpose(b)

AttributeError: module 'numpy' has no attribute 'Transpose'

In [44]:
np.insert(a,1,5)

array([1, 5, 2, 3])

In [45]:
a.ravel()

array([1, 2, 3])

In [46]:
a

array([1, 2, 3])

In [47]:
a.reshape(3,-2)

array([[1],
       [2],
       [3]])

In [48]:
a.ravel()

array([1, 2, 3])

In [49]:
a.resize()

In [50]:
a

array([1, 2, 3])

In [51]:
np.hsplit(a,3)

[array([1]), array([2]), array([3])]

In [52]:
np.vsplit(a)

TypeError: vsplit() missing 1 required positional argument: 'indices_or_sections'

In [54]:
import pandas as pd
data=pd.Series([.25,.6,.32])

In [56]:
data.values

array([0.25, 0.6 , 0.32])

In [57]:
data=pd.Series([.35,.5,.6])
index=([1,2,3,4])

In [59]:
data(5)

TypeError: 'Series' object is not callable

In [60]:
area_dict={'ram':45,'sam':47,'kam':49}

In [61]:
pd.Series(area_dict)

ram    45
sam    47
kam    49
dtype: int64

In [64]:
x=pd.dataframe({'ram':45,'karan':49})

AttributeError: module 'pandas' has no attribute 'dataframe'

In [65]:
df = pd.DataFrame(
{"a" : [4 ,5, 6],
"b" : [7, 8, 9],
"c" : [10, 11, 12]},
index = [1, 2, 3])

In [66]:
df

a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [67]:
data=[{'a':1,b:2}]

TypeError: unhashable type: 'numpy.ndarray'

In [73]:
population_dict={'california':3333,
                  'texas':2222,
                   'newyork':34442,
                   'florida':4455,
                    'illusion':32203}
population=pd.DataFrame(population_dict)

ValueError: If using all scalar values, you must pass an index

In [74]:
population

california     3333
texas          2222
newyork       34442
florida        4455
illusion      32203
dtype: int64