In [1]:
import numpy as np

In [2]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [3]:
np.zeros(10,dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [4]:
np.empty(3)

array([1., 1., 1.])

In [5]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.full((3,4),3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [8]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
np.random.random((3,2))

array([[0.86242158, 0.40233854],
       [0.38523903, 0.9364049 ],
       [0.00827062, 0.28595909]])

In [13]:
x=np.random.randint(10,size=(6))

In [14]:
x

array([2, 5, 4, 0, 0, 0])

In [15]:
x[:5]

array([2, 5, 4, 0, 0])

In [16]:
x[5:]

array([0])

In [18]:
x([1::2])

SyntaxError: invalid syntax (<ipython-input-18-0d4f61e4a2b7>, line 1)

In [19]:
x2[::-1,::-1]

NameError: name 'x2' is not defined

In [20]:
a=[[1,2]]

In [21]:
np.array(a)

array([[1, 2]])

In [22]:
a

[[1, 2]]

In [23]:
a[:]

[[1, 2]]

In [24]:
a[:-2]

[]

In [25]:
a[:,0]

TypeError: list indices must be integers or slices, not tuple

In [26]:
b[1,2]

NameError: name 'b' is not defined

In [27]:
np.conconate((a,b))

AttributeError: module 'numpy' has no attribute 'conconate'

In [28]:
a

[[1, 2]]

In [29]:
np.vsplit(a,3)

AttributeError: 'list' object has no attribute 'shape'

In [32]:
#numpy date and time
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [42]:
b=np.array([[1,2,3,4,4],[1,2,3,4,5]])

In [43]:
b

array([[1, 2, 3, 4, 4],
       [1, 2, 3, 4, 5]])

In [44]:
a[2]

3

In [45]:
a[1]

2

In [46]:
a[0]

1

In [48]:
b[1,2]

3

In [49]:
a[0:2]

array([1, 2])

In [50]:
a[::-1]

array([4, 3, 2, 1])

In [51]:
a

array([1, 2, 3, 4])

In [52]:
b[:1]

array([[1, 2, 3, 4, 4]])

In [53]:
b

array([[1, 2, 3, 4, 4],
       [1, 2, 3, 4, 5]])

In [54]:
a[a<2]

array([1])

In [55]:
a[::-1]

array([4, 3, 2, 1])

In [56]:
a[a<2]

array([1])

In [57]:
a

array([1, 2, 3, 4])

In [59]:
i=np.traspose(b)

AttributeError: module 'numpy' has no attribute 'traspose'

In [60]:
b.resize((2,6))

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [61]:
np.hsplit(a,3)

ValueError: array split does not result in an equal division

In [62]:
np.vsplit(c,2)

NameError: name 'c' is not defined

In [63]:
print(np.arange['2017-05','2017-04',dtype='datetime64[D]'])

SyntaxError: invalid syntax (<ipython-input-63-4308f308f232>, line 1)

In [75]:
import datetime
import timedelta
import numpy as np

ModuleNotFoundError: No module named 'timedelta'

In [76]:
yesterdy=np.datetime64('today','D')-np.timedelta(1,'D')
print('yesterday',yesterday)

AttributeError: module 'numpy' has no attribute 'timedelta'

In [77]:
today=np.datetime64('today','D')

In [78]:

print('Today',today)


Today 2020-09-19


In [81]:
tommrow=np.datetime('today','D')+np.datetime64(1,'D')

AttributeError: module 'numpy' has no attribute 'datetime'

In [82]:
#numpy program count the no of days of the given month
print('number of days in febraury 2016')
print(np.datetime64('2016-03-01')-np.datetime64('2020-03-04'))

number of days in febraury 2016
-1464 days


In [ ]:
import numpy as np
import datetime 
start=datetime.datetime(2000,1,1)
dt_array=np.array([start+datetime.timedelta])

In [83]:
#numpy program find first monday of 2017
import numpy as np

In [84]:
print('first monday in 2017')

first monday in 2017


In [85]:
print(np.busday_offset('2017-05'),roll='forward',weekmask='mon')

TypeError: busday_offset() missing required argument 'offsets' (pos 2)

In [86]:
import numpy as np

In [87]:
p=[[0,1],[1,0]]
q=[[1,2],[2,3]]

In [88]:
result=np.dot(p,q)

In [89]:
result

array([[2, 3],
       [1, 2]])

In [90]:
reu=np.cross(p,q)

In [132]:
np.datetime64('today','D')

numpy.datetime64('2020-09-19')

In [92]:
res=np.inner(p,q)

In [94]:
res

array([[2, 3],
       [1, 2]])

In [99]:
#eign value and eign vector
w,v=np.linalg.eig(a,b)

TypeError: eig() takes 1 positional argument but 2 were given

In [101]:
result=np.knon(a,b)

AttributeError: module 'numpy' has no attribute 'knon'

In [102]:
result

array([[2, 3],
       [1, 2]])

In [103]:
#determent of the array
a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [104]:
result=np.linalg.det(a)

In [106]:
result

-2.0000000000000004

In [107]:
#find decompostion of the matrix
a=np.linalg.qr(result)

LinAlgError: 0-dimensional array given. Array must be two-dimensional

In [108]:
result=np.linalg.inv(a)

In [109]:
result

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [110]:
#sum of the diagonal of the matrix
result=np.trace(a)

In [111]:
result

5

In [112]:
a

array([[1, 2],
       [3, 4]])

In [114]:
x=np.arange(7)

In [115]:
x

array([0, 1, 2, 3, 4, 5, 6])

In [116]:
print(np.power(x,3))

[  0   1   8  27  64 125 216]


In [117]:
print(np.true_divide(x,3))

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.        ]


In [118]:
print(np.absolute(x))

[0 1 2 3 4 5 6]


In [119]:
print(np.reminder(x,5))

AttributeError: module 'numpy' has no attribute 'reminder'

In [120]:
#round the array of the element
print(np.round([.5,5,5,5,4]))

[0. 5. 5. 5. 4.]


In [122]:
print(np.absoluate(x))

AttributeError: module 'numpy' has no attribute 'absoluate'

In [123]:
np.floor(x)

array([0., 1., 2., 3., 4., 5., 6.])

In [124]:
np.ceil(x)

array([0., 1., 2., 3., 4., 5., 6.])

In [125]:
x=np.random.random((5,3))

In [126]:
x

array([[0.17196266, 0.99157745, 0.03033035],
       [0.34730039, 0.61585518, 0.23500382],
       [0.95726258, 0.41860608, 0.77476485],
       [0.18057406, 0.18569442, 0.22551254],
       [0.24854794, 0.59409321, 0.2237922 ]])

In [127]:
print(x)

[[0.17196266 0.99157745 0.03033035]
 [0.34730039 0.61585518 0.23500382]
 [0.95726258 0.41860608 0.77476485]
 [0.18057406 0.18569442 0.22551254]
 [0.24854794 0.59409321 0.2237922 ]]


In [128]:
#compute the polynomial value
print(np.polyval([1,-2,1],2))

1


In [129]:
print(np.polyval([1,-12,0],3))

-27


In [130]:
np.exp(x)

array([[1.18763349, 2.6954831 , 1.030795  ],
       [1.41524179, 1.85123907, 1.2649136 ],
       [2.60455694, 1.51984155, 2.17008177],
       [1.19790484, 1.20405427, 1.25296475],
       [1.28216229, 1.81138765, 1.25081108]])

In [133]:
r1=np.signbit(x)

In [135]:
r1

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [138]:
#np.seed(42)

In [139]:
df = pd.DataFrame(
{"a" : [4 ,5, 6],
"b" : [7, 8, 9],
"c" : [10, 11, 12]},
index = [1, 2, 3])

NameError: name 'pd' is not defined

In [140]:
pd.dataframe{['a':1,'b':2]}

SyntaxError: invalid syntax (<ipython-input-140-e23c301da141>, line 1)

In [141]:
pd.DataFrame({'population':population,'area':area})

NameError: name 'pd' is not defined

In [142]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
#series speclized dictonery
population_dict={'california':3333,
                  'texas':2222,
                   'newyork':}